name: Checkout and Upload Code as Artifact

on:
  workflow_dispatch:

jobs:
  checkout-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from the source repository
      - name: Checkout Source Repository
        uses: actions/checkout@v3
        with:
          repository: VarshaK3222/CrossBT # Replace with the owner/repo of the private source repository
          token: ${{ secrets.SOURCE_REPO_PAT }} # Use the PAT stored as a secret
          path: source-code # Checkout to a folder named "source-code"

      # Step 2: Upload source code as an artifact
      - name: Upload as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: source-code-artifact
          path: source-code/ # Upload the checked-out source code
